version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "azad123"
      ACCEPT_EULA: "Y"
    ports:
      - "21433:1433"
    restart: unless-stopped
    networks:
      - webnet

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/Apps/CovidClinic.Api/Dockerfile
    ports:
      #- "5006:443"
      - "5005:80"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=5006
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=azad123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/CovidClinic.pfx
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=CovidClinicDb;User=sa;Password=azad123;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
    #volumes:
      #- ./https/CovidClinic.pfx:/https/CovidClinic.pfx:ro
    restart: on-failure
    networks:
      - webnet
    depends_on:
      - sql-server-db

volumes:
  data01:
    driver: local

networks:
  webnet:
    driver: bridge
